### ISSUE TITLE
Optional parameters should always be last in signatures

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/IntervalParser#13]
Currently the signature of the constructor of the `IntervalParser\TimeInterval` has a required parameter _after_ optional parameters:

```
__construct(int $intervalOffset, int $intervalLength, string $leadingData  = null, string $trailingData = null, $interval)
```

This effectively makes the two optional parameters mandatory, because there is no way to not pass them in resulting in having to pass `null`s when it is not needed. E.g.:

```
new TimeInterval(7, 24, null, null, new DateInterval());
```

while you could just pass:

```
new TimeInterval(7, 24, new DateInterval());
```

if the optional parameters are last.

**Comment by ekinhbayar** [comment]
Ugh, very much agreed. I think this commit closes this issue ^^,

**Comment by PeeHaa** [comment]
Yes looks like that fixes it. 👍
